org.gradle.jvmargs=-Xmx1200m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
android.aapt2FromMavenOverride=/usr/local/bin/aapt2
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
